title: MKMŽ Slivenec
description: Stránky MKMŽ Slivenec
baseurl: ""  # the subpath of your site, e.g. /blog
url: "https://achlyhere.github.io/MKMZ-Slivenec"  # the base hostname & protocol for your site
theme: minima

# Build settings
markdown: kramdown