sass:
  sass_dir: assets/_scss
  style: compressed

include:
  - .htaccess
  - assets/css

collections:
  my_collection:
    output: true

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
