sass:
  sass_dir: assets/scss
  style: compressed

include:
  - .htaccess

collections:
  my_collection:
    output: true

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

baseurl: ""
url: ""

# Additional settings for SCSS and file cooperation
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - _site
  - .jekyll-cache
  - .jekyll-metadata
  - .sass-cache
  - .env
  - .env.*
  - .DS_Store
  - Thumbs.db
