title: "Your Site Title"
description: "A description of your site"
baseurl: "" # Adjust based on your deployment scenario
url: "http://localhost:4000" # Adjust based on your domain

sass:
  sass_dir: assets/css/_sass
  style: compressed

collections:
  pages:
    output: true

include:
  - assets/css
  - assets/css/_sass
  - assets/images/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-sass-converter

# Other configurations...