# SASS settings
sass:
  sass_dir: _sass
  style: compressed

# Include additional files
include:
  - .htaccess

# Collections settings
collections:
  my_collection:
    output: true

# Build settings
markdown: kramdown

# Site settings
title: MKMZ Slivenec
description: Stránky MKMZ Slivenec
baseurl: ""  # The subpath of your site, e.g., /blog
url: "https://yourusername.github.io"  # The base hostname & protocol for your site
theme: minima

# Plugins to use
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude files from the build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle
  - .gitignore
  - .github